micronaut:
    application:
        name: bookcatalogue  # used as service name in consul
#    server:
#        port: 8081


dataSource:
    pooled: true
#    dbCreate: create-drop
    dbCreate: update
    url: jdbc:mysql://127.0.0.1:3306/testmicronaut
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: root
    password: mysql
    # enable sql logging
    logSql: true
    formatSql: true

hibernate:
    show_sql: true
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory


# logs the SQL statements
log4j.logger.org.hibernate.SQL: debug
# Logs the JDBC parameters passed to a query
log4j.logger.org.hibernate.type: debug
