micronaut:
    server:
        port: -1

dataSource:
    pooled: true
    dbCreate: create
    url: jdbc:h2:mem:testDb
    driverClassName: org.h2.Driver
    username: sa
    password:
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
